test1:
  image: docker:latest
  services:
  - docker:dind

  variables:
    RELEASE_IMAGE: registry.gitlab.com/sw-archive/di-msc/thesis/hate_speech:latest

  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN gitlab.com

  stage: build
  script:
    - docker build --pull -t $RELEASE_IMAGE .
    - docker push $RELEASE_IMAGE

    only:
      - master

test:
  image: python:3.7
  stage: test
  script:
  - pip install -r requirements.txt
  - sphinx-build -b html -a ./docs/source public
  only:
  - branches
  except:
  - master

pages:
  image: python:3.7
  stage: deploy
  script:
  - pip install -r requirements.txt
  - sphinx-build -b html -a ./docs/source public
  artifacts:
    paths:
    - public
  only:
  - master
