# Generated by Django 3.0.3 on 2020-03-01 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('num_labels', models.IntegerField()),
                ('language', models.CharField(max_length=255)),
                ('label1', models.CharField(max_length=255)),
                ('label2', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'datasets',
            },
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('text', models.CharField(max_length=4000)),
                ('preprocessed_text', models.CharField(max_length=4000)),
                ('label', models.CharField(max_length=255)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='hate_speech_detection.Dataset')),
            ],
            options={
                'db_table': 'tweets',
            },
        ),
    ]
