# Generated by Django 3.0.3 on 2020-03-01 11:18
import json
from os import listdir
from os.path import join

from django.core.exceptions import EmptyResultSet, ObjectDoesNotExist, MultipleObjectsReturned
from django.db import migrations

from hate_speech.settings import BASE_DIR

resources_folder = "resources"
datasets_folder_name = "datasets"
datasets_folder = join(BASE_DIR, resources_folder, datasets_folder_name)


def save_tweets(apps, schema_editor):
    Dataset = apps.get_model('hate_speech_detection', 'Dataset')
    Tweet = apps.get_model('hate_speech_detection', 'Tweet')
    try:
        datasets = Dataset.objects.all()
    except (EmptyResultSet, ObjectDoesNotExist, MultipleObjectsReturned, Exception):
        datasets = None
    if not datasets:
        for file in listdir(datasets_folder):
            file_path = join(datasets_folder, file)
            with open(file_path, "r") as f:
                content = json.loads(f.read())
            dataset = Dataset()
            dataset.name = file
            dataset.num_labels = content["num_labels"]
            dataset.language = content["language"]
            for i in range(dataset.num_labels):
                if i == 0:
                    dataset.label1 = content["label_names"][i]
                elif i == 1:
                    dataset.label2 = content["label_names"][i]
            dataset.save()
            for datum in content["data"]["train"]:
                tweet = Tweet()
                tweet.dataset = dataset
                tweet.text = datum["text"]
                tweet.label = datum["labels"][0]
                tweet.save()


class Migration(migrations.Migration):
    dependencies = [
        ('hate_speech_detection', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(save_tweets),
    ]
