# Generated by Django 3.0.3 on 2020-03-01 11:18

import re
import string
from os.path import join

from django.db import migrations

from hate_speech.settings import BASE_DIR, all_properties


class Preprocessor:
    resources_folder = "resources"
    stopwords_folder = "stopwords"
    stopwords_file = "stopwords.txt"

    def __init__(self):
        self.stopwords = set(self.load_stopwords())
        self.stopwords_to_be_removed = all_properties["preprocessing"]["remove_stopwords"]
        self.punct_digit_to_space = str.maketrans(string.punctuation + string.digits,
                                                  " " * len(string.punctuation + string.digits))

    def load_stopwords(self):
        path_to_file = join(BASE_DIR, self.resources_folder, self.stopwords_folder, self.stopwords_file)
        with open(path_to_file, "r") as f:
            lines = f.readlines()
            final_lines = []
            for line in lines:
                final_lines.append(line.lower())
            return final_lines

    def preprocess(self, Tweet):
        tweets = Tweet.objects.all()
        for tweet in tweets:
            if self.stopwords_to_be_removed:
                preprocessed_text = self.remove_stopwords(tweet.text)
            else:
                preprocessed_text = tweet.text
            preprocessed_text = preprocessed_text.translate(self.punct_digit_to_space).strip()
            preprocessed_text = re.sub("[ ]+", " ", preprocessed_text)
            tweet.preprocessed_text = preprocessed_text
            tweet.save()

    def remove_stopwords(self, text):
        text_words = text.split()
        text_words = [word for word in text_words if word.lower() not in self.stopwords]
        return ' '.join(text_words)


def preprocess_tweets(apps, schema_editor):
    Tweet = apps.get_model('hate_speech_detection', 'Tweet')
    preprocessor = Preprocessor()
    preprocessor.preprocess(Tweet=Tweet)


class Migration(migrations.Migration):
    dependencies = [
        ('hate_speech_detection', '0002_auto_save_tweets'),
    ]

    operations = [
        migrations.RunPython(preprocess_tweets),
    ]
